## Operaciones entre arrays: vectorización

En otros lenguajes de programación, las operaciones entre vectores requieren el uso de bucles para recorrerlos, acumular valores, crear los nuevos resultados, etc. Esto puede ser ineficiente. Veamos un ejemplo:


In [1]:
import numpy as np
import time
#sumar dos arrays
numElementos = 500
a1 = np.random.rand(numElementos)
a2 = np.random.rand(numElementos)
a3 = np.zeros(numElementos)
inicio = time.time()
for i in range(a1.shape[0]):
    a3[i] = a1[i] + a2[i]
fin = time.time()
print("Tiempo: " , (fin - inicio) * 1000 , " ms")

Tiempo:  0.3447532653808594  ms


## Vectorización

Una de las ventajas que aportan los arrays de numpy es la facilidad para realizar operaciones sobre el array completo sin tener que indicarlo elemento a elemento.

La vectorización permite expresar operaciones entre arrays sin usar bucles for. Más concretamente, podemos realizar operaciones aritméticas entre arrays del mismo tamaño para que se apliquen elemento a elemento, indicando solamente la operación a realizar entre los vectores. Como resultado, la operación se aplicará a todos los elementos.

Por un lado, la vectorización nos permite escribir un código más fácil de entender. Pero la mayor ventaja es en cuanto a rendimiento.

Aquí encontramos una diferencia con las listas de python al usar el operador +. En las listas, + sirve para añadir elementos. Con los arrays de numpy el operador + sirve para sumar.

In [2]:
inicio = time.time()
a3 = a1 + a2
fin = time.time()
print("Tiempo: " , (fin - inicio) * 1000 , " ms")

Tiempo:  0.07653236389160156  ms


Veamos más ejemplos con operaciones entre vectores

In [3]:
alturas = [180, 215, 210, 210, 188, 176, 209, 200]
npAlturas = np.array(alturas)
pesos = [81, 97.5, 95, 95.5, 85, 79, 94, 90]
npPesos = np.array(pesos)

#el operador + se comporta de forma distinta
#en numpy sumamos arrays, con listas las unimos
l1 = alturas + pesos
print (l1)
a1 = npAlturas + npPesos
print (a1)

[180, 215, 210, 210, 188, 176, 209, 200, 81, 97.5, 95, 95.5, 85, 79, 94, 90]
[261.  312.5 305.  305.5 273.  255.  303.  290. ]


In [4]:
#vamos a calcular el índice de masa corporal

#altura la dividimos entre 100 para obtener el valor en metros
imc = npPesos / ((npAlturas / 100.0 ) **2)

print (imc)

[25.         21.09248242 21.54195011 21.6553288  24.04934359 25.5036157
 21.51965385 22.5       ]


También podemos realizar operaciones entre arrays de distintas dimensiones. Por ejemplo, si realizamos una operación entre un array de dos dimensiones con uno de una dimensión, la operación se realiza entre cada fila del array de dos dimensiones y el array pasado como operando

In [5]:
#combinaciones de cálculos con dos dimensiones
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

#se multiplican todos los elementos por dos
print (np_mat * 2)

#al primer elemento de cada fila se le suma 10 y al segundo se le suma 1
print (np_mat + np.array([[10],[2],[3]]))

#se suman los elementos de cada posición
print (np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [ 5  6]
 [ 8  9]]
[[ 2  4]
 [ 6  8]
 [10 12]]


### Ejercicio

1. Sumar arrays de apartados anteriores con  la mismas dimensiones
2. Realiza los siguientes pasos:

    2.1. Crea un array de unos de una sola dimensión (m,)
    
    2.2. Crea un array de dos dimensiones con valores aleatorios. La segunda dimensión debe tener el mismo número de elementos que el array del punto 2.1. (n,m)
    
    2.3. Suma los dos arrays. ¿Qué ha ocurrido?