# NumPy 

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[-0.17182957,  0.85885742, -0.70340933],
       [-0.66523411, -1.40048476, -0.86667077]])

In [3]:
data * 10

array([[ -1.71829575,   8.58857416,  -7.03409333],
       [ -6.6523411 , -14.00484757,  -8.66670774]])

In [4]:
data -1

array([[-1.17182957, -0.14114258, -1.70340933],
       [-1.66523411, -2.40048476, -1.86667077]])

In [5]:
data / 0.1

array([[ -1.71829575,   8.58857416,  -7.03409333],
       [ -6.6523411 , -14.00484757,  -8.66670774]])

In [6]:
data + data

array([[-0.34365915,  1.71771483, -1.40681867],
       [-1.33046822, -2.80096951, -1.73334155]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
data1 = [6,7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
arr1

(5,)
float64
1


array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
arr2

(2, 4)
int64
2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
np.zeros((2,3,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [13]:
np.empty((2,2,3,6))

array([[[[-3.10503618e+231,  3.11107843e+231,  6.92781300e-310,
           6.92781300e-310,  6.92781300e-310,  2.12199580e-314],
         [ 0.00000000e+000,  3.95252517e-323,  6.92767966e-310,
           6.92780764e-310,  6.92781225e-310,  0.00000000e+000],
         [ 6.92781215e-310,  0.00000000e+000,  0.00000000e+000,
           4.94065646e-324,  0.00000000e+000,  4.24399159e-314]],

        [[ 0.00000000e+000,  7.55430502e-312,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000]]],


       [[[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000, -3.10503618e+231, -3.10503618e+231],
         [ 2.19957610e-314,  4.94065646e-323,  5.43472210e-323,
                       nan,

In [14]:
np.arange(15,-7,-2)

array([15, 13, 11,  9,  7,  5,  3,  1, -1, -3, -5])

We can specify the desired dtype of an array:

In [15]:
arr1 = np.array([1, 2, 3], dtype=np.int32)
print(arr1)
arr2 = np.array([1, 2, 3], dtype=np.float64)
print(arr2)

[1 2 3]
[1. 2. 3.]


In [16]:
arr2.astype(np.int8)

array([1, 2, 3], dtype=int8)

In [17]:
arr3 = np.array([200.01926, 256, 255, 128], dtype=np.float64)
print(arr3)

[200.01926 256.      255.      128.     ]


In [18]:
arr3.astype(np.int8)

array([ -56,    0,   -1, -128], dtype=int8)

In [19]:
arr3.astype(np.uint8)

array([200,   0, 255, 128], dtype=uint8)

In [20]:
arr = np.random.randn(3,4)
arr

array([[ 1.33027123,  0.80136202, -0.33879193, -1.32299692],
       [-1.18651099,  0.53597335, -1.27935946,  0.55591034],
       [ 0.36411343,  0.23303489, -0.29858412, -0.48415915]])

In [21]:
inds = [5, 0, 2, 11]
arr.take(inds)

array([ 0.53597335,  1.33027123, -0.33879193, -0.48415915])

In [22]:
inds = [2, 0, 1, 2, 3]
arr.take(inds, axis=1)

array([[-0.33879193,  1.33027123,  0.80136202, -0.33879193, -1.32299692],
       [-1.27935946, -1.18651099,  0.53597335, -1.27935946,  0.55591034],
       [-0.29858412,  0.36411343,  0.23303489, -0.29858412, -0.48415915]])

In [23]:
inds = [2, 0, 1, 2]
arr.take(inds, axis=0)

array([[ 0.36411343,  0.23303489, -0.29858412, -0.48415915],
       [ 1.33027123,  0.80136202, -0.33879193, -1.32299692],
       [-1.18651099,  0.53597335, -1.27935946,  0.55591034],
       [ 0.36411343,  0.23303489, -0.29858412, -0.48415915]])

In [24]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [25]:
col.shape

(4,)

In [26]:
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr[1:3, 1:2] = 5
arr

array([[0., 0., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [28]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [29]:
arr[:, :1] = col[:, np.newaxis]
arr

array([[ 1.28,  0.  ,  0.  ],
       [-0.42,  5.  ,  0.  ],
       [ 0.44,  5.  ,  0.  ],
       [ 1.6 ,  0.  ,  0.  ]])

In [30]:
arr[:1] = col[np.newaxis, :3]
arr

array([[ 1.28, -0.42,  0.44],
       [-0.42,  5.  ,  0.  ],
       [ 0.44,  5.  ,  0.  ],
       [ 1.6 ,  0.  ,  0.  ]])

In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [32]:
data = np.random.randn(7, 4)

In [33]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [34]:
data

array([[-0.84974397, -0.15104742,  2.13613138, -1.22231653],
       [ 0.29037071,  1.90279204,  0.58346711, -0.39306693],
       [-2.2430906 , -0.18195483, -1.27605966,  0.44338439],
       [-0.95785128,  0.16611732, -0.68642908, -1.04744803],
       [ 0.43868405, -0.56276216,  1.82510576,  0.42641483],
       [-0.12439946, -0.89227987, -0.0356442 ,  1.19989034],
       [-0.03666656,  0.44478042,  1.7923638 , -0.11175583]])

In [35]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [36]:
data[names == 'Bob']

array([[-0.84974397, -0.15104742,  2.13613138, -1.22231653],
       [-0.95785128,  0.16611732, -0.68642908, -1.04744803]])

In [37]:
names[:4] == 'Bob'

array([ True, False, False,  True])

In [38]:
data[:, names[:4] == 'Bob']

array([[-0.84974397, -1.22231653],
       [ 0.29037071, -0.39306693],
       [-2.2430906 ,  0.44338439],
       [-0.95785128, -1.04744803],
       [ 0.43868405,  0.42641483],
       [-0.12439946,  1.19989034],
       [-0.03666656, -0.11175583]])

In [39]:
data[:, ~(names[:4] == 'Bob')]

array([[-0.15104742,  2.13613138],
       [ 1.90279204,  0.58346711],
       [-0.18195483, -1.27605966],
       [ 0.16611732, -0.68642908],
       [-0.56276216,  1.82510576],
       [-0.89227987, -0.0356442 ],
       [ 0.44478042,  1.7923638 ]])

In [40]:
data[:, names[:4] != 'Bob']

array([[-0.15104742,  2.13613138],
       [ 1.90279204,  0.58346711],
       [-0.18195483, -1.27605966],
       [ 0.16611732, -0.68642908],
       [-0.56276216,  1.82510576],
       [-0.89227987, -0.0356442 ],
       [ 0.44478042,  1.7923638 ]])

### Array Oriented Ptogramming:

Calculate sqrt(x^2 + y^2) of every combination of a 1D array:
-5:5

In [41]:
points = np.arange(-5, 5)

In [42]:
xs, ys = np.meshgrid(points, points)

In [43]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [44]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [45]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [46]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [47]:
xs.sum(0)

array([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40])

In [48]:
xs.sum(1)

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5])