# NumPy 

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)
data

array([[ 0.76921103,  0.20896196,  0.7699903 ],
       [-0.52286737, -0.50035559, -0.78616122]])

In [3]:
data * 10

array([[ 7.69211034,  2.08961964,  7.69990298],
       [-5.22867368, -5.0035559 , -7.86161225]])

In [5]:
data -1

array([[-0.23078897, -0.79103804, -0.2300097 ],
       [-1.52286737, -1.50035559, -1.78616122]])

In [6]:
data / 0.1

array([[ 7.69211034,  2.08961964,  7.69990298],
       [-5.22867368, -5.0035559 , -7.86161225]])

In [7]:
data + data

array([[ 1.53842207,  0.41792393,  1.5399806 ],
       [-1.04573474, -1.00071118, -1.57232245]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [14]:
data1 = [6,7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)
arr1

(5,)
float64
1


array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)
arr2

(2, 4)
int64
2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.zeros((2,3,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [32]:
np.empty((2,2,3,6))

array([[[[-2.31584178e+077, -2.31584178e+077,  1.77863633e-322,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           5.49109388e-143, -2.31584178e+077, -2.31584178e+077]],

        [[ 1.38338381e-322,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
           0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
         [ 0.00000000e+000,  9.58487353e-322, -2.31584178e+077,
          -2.31584178e+077,  9.88131292e-323,  1.16097020e-028]]],


       [[[ 9.15559261e-072,  2.73744381e-052,  3.31484178e-033,
           5.01163173e+217,  8.37170074e-144,  3.27612667e+179],
         [ 7.48391434e-067,  4.51444022e-090,  3.72595843e-057,
           5.01163114e+217,

In [37]:
np.arange(15,-7,-2)

array([15, 13, 11,  9,  7,  5,  3,  1, -1, -3, -5])

We can specify the desired dtype of an array:

In [73]:
arr1 = np.array([1, 2, 3], dtype=np.int32)
print(arr1)
arr2 = np.array([1, 2, 3], dtype=np.float64)
print(arr2)

[1 2 3]
[1. 2. 3.]


In [81]:
arr2.astype(np.int8)

array([1, 2, 3], dtype=int8)

In [100]:
arr3 = np.array([200.01926, 256, 255, 128], dtype=np.float64)
print(arr3)

[200.01926 256.      255.      128.     ]


In [101]:
arr3.astype(np.int8)

array([ -56,    0,   -1, -128], dtype=int8)

In [102]:
arr3.astype(np.uint8)

array([200,   0, 255, 128], dtype=uint8)

In [103]:
arr = np.random.randn(3,4)
arr

array([[ 0.3393776 ,  1.39458537,  0.65577137,  1.60650885],
       [ 0.48421916, -1.00115491,  0.49855372, -0.50687776],
       [-0.46455502,  0.54898896,  1.47142661, -0.4244108 ]])

In [106]:
inds = [5, 0, 2, 11]
arr.take(inds)

array([-1.00115491,  0.3393776 ,  0.65577137, -0.4244108 ])

In [113]:
inds = [2, 0, 1, 2, 3]
arr.take(inds, axis=1)

array([[ 0.65577137,  0.3393776 ,  1.39458537,  0.65577137,  1.60650885],
       [ 0.49855372,  0.48421916, -1.00115491,  0.49855372, -0.50687776],
       [ 1.47142661, -0.46455502,  0.54898896,  1.47142661, -0.4244108 ]])

In [115]:
inds = [2, 0, 1, 2]
arr.take(inds, axis=0)

array([[-0.46455502,  0.54898896,  1.47142661, -0.4244108 ],
       [ 0.3393776 ,  1.39458537,  0.65577137,  1.60650885],
       [ 0.48421916, -1.00115491,  0.49855372, -0.50687776],
       [-0.46455502,  0.54898896,  1.47142661, -0.4244108 ]])

In [127]:
col = np.array([1.28, -0.42, 0.44, 1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [117]:
col.shape

(4,)

In [154]:
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [155]:
arr[1:3, 1:2] = 5
arr

array([[0., 0., 0.],
       [0., 5., 0.],
       [0., 5., 0.],
       [0., 0., 0.]])

In [156]:
col[:, np.newaxis]

array([[ 1.28],
       [-0.42],
       [ 0.44],
       [ 1.6 ]])

In [157]:
arr[:, :1] = col[:, np.newaxis]
arr

array([[ 1.28,  0.  ,  0.  ],
       [-0.42,  5.  ,  0.  ],
       [ 0.44,  5.  ,  0.  ],
       [ 1.6 ,  0.  ,  0.  ]])

In [162]:
arr[:1] = col[np.newaxis, :3]
arr

array([[ 1.28, -0.42,  0.44],
       [-0.42,  5.  ,  0.  ],
       [ 0.44,  5.  ,  0.  ],
       [ 1.6 ,  0.  ,  0.  ]])

In [163]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [164]:
data = np.random.randn(7, 4)

In [166]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [168]:
data

array([[-0.87726471, -0.40735941,  2.9522926 ,  1.03900554],
       [-1.55088374, -0.29764404, -0.67700817,  0.73924563],
       [ 0.1065515 , -0.29440137,  0.58296894, -0.82637844],
       [-0.43259342, -0.2901101 , -1.43970514,  1.25187213],
       [-0.95733267, -0.64950374,  0.40174237,  0.75865902],
       [-1.10432866, -0.14677146,  1.38910939,  0.04521569],
       [ 0.17618899,  0.98063518,  1.06172838, -0.02131229]])

In [167]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [169]:
data[names == 'Bob']

array([[-0.87726471, -0.40735941,  2.9522926 ,  1.03900554],
       [-0.43259342, -0.2901101 , -1.43970514,  1.25187213]])

In [175]:
names[:4] == 'Bob'

array([ True, False, False,  True])

In [176]:
data[:, names[:4] == 'Bob']

array([[-0.87726471,  1.03900554],
       [-1.55088374,  0.73924563],
       [ 0.1065515 , -0.82637844],
       [-0.43259342,  1.25187213],
       [-0.95733267,  0.75865902],
       [-1.10432866,  0.04521569],
       [ 0.17618899, -0.02131229]])

In [177]:
data[:, ~(names[:4] == 'Bob')]

array([[-0.40735941,  2.9522926 ],
       [-0.29764404, -0.67700817],
       [-0.29440137,  0.58296894],
       [-0.2901101 , -1.43970514],
       [-0.64950374,  0.40174237],
       [-0.14677146,  1.38910939],
       [ 0.98063518,  1.06172838]])

In [178]:
data[:, names[:4] != 'Bob']

array([[-0.40735941,  2.9522926 ],
       [-0.29764404, -0.67700817],
       [-0.29440137,  0.58296894],
       [-0.2901101 , -1.43970514],
       [-0.64950374,  0.40174237],
       [-0.14677146,  1.38910939],
       [ 0.98063518,  1.06172838]])

### Array Oriented Ptogramming:

Calculate sqrt(x^2 + y^2) of every combination of a 1D array:
-5:5

In [189]:
points = np.arange(-5, 5)

In [190]:
xs, ys = np.meshgrid(points, points)

In [191]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [192]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [194]:
z = np.sqrt(xs**2 + ys**2)
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [196]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [201]:
xs.sum(0)

array([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40])

In [198]:
xs.sum(1)

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5])